#version: '3'

services:
  redis:
    image: redis:7.0-alpine
    ports:
      - '6379:6379'
    networks:
      - stalkerz
  backend-spring:
    build: '.'
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - stalkerz
  frontend:
    build: 'src/frontend/'
    volumes:
      - './src/frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - backend-spring
      - redis
#    РЕСТАРТ ЕСЛИ ОШИБка
#    restart: unless-stopped
    networks:
      - stalkerz
networks:
  stalkerz:
    driver: 'bridge'